public with sharing class MM_GetActorDetailsResponse {
    public boolean adult;
    @AuraEnabled
    public String biography;	//Scarlett Johansson, born November 22, 1984, is an American actress, model and singer. She made her film debut in North (1994) and was later nominated for the Independent Spirit Award for Best Female Lead for her performance in Manny & Lo (1996), garnering further acclaim and prominence with roles in The Horse Whisperer (1998) and Ghost World (2001). She shifted to adult roles with her performances in Girl with a Pearl Earring (2003) and Sofia Coppola's Lost in Translation (2003), for which she won a BAFTA award for Best Actress in a Leading Role; both films earned her Golden Globe Award nominations as well.
    @AuraEnabled
    public String birthday;	//1984-11-22
    public Integer gender;	//1
    @AuraEnabled
    public Integer id;	//1245
    public String imdb_id;	//nm0424060
    public String known_for_department;	//Acting
    @AuraEnabled
    public String name;	//Scarlett Johansson
    @AuraEnabled
    public String place_of_birth;	//New York City, New York, USA
    public Double popularity;	//71.497
    public String profile_path;	///6NsMbJXRlDZuDzatN2akFdGuTvx.jpg
}