public with sharing class MM_GetTrailerCalloutResponse {
    public Integer id;	//379686
    public cls_results[] results;
    class cls_results {
        public String id;	//606868331cc4ff0058198cb6
        public String iso_639_1;	//en
        public String iso_3166_1;	//US
        @AuraEnabled
        public String key;	//olXYZOsXw_o
        public String name;	//Trailer 1
        public String site;	//YouTube
        public Integer size;	//1080
        public String type;	//Trailer
    }
}