public with sharing class MM_GetSingleMovieCalloutResponse {
    public boolean adult;
    public String backdrop_path;	///keIxh0wPr2Ymj0Btjh4gW7JJ89e.jpg
    public Integer budget;	//200000000
    public String homepage;	//https://www.marvel.com/movies/black-widow
    @AuraEnabled
    public Integer id;	//497698
    @AuraEnabled
    public Boolean favorite;
    @AuraEnabled
    public Boolean blackListed;
    public String imdb_id;	//tt3480822
    public String original_language;	//en
    public String original_title;	//Black Widow
    @AuraEnabled
    public String overview;	//Natasha Romanoff, also known as Black Widow, confronts the darker parts of her ledger when a dangerous conspiracy with ties to her past arises. Pursued by a force that will stop at nothing to bring her down, Natasha must deal with her history as a spy and the broken relationships left in her wake long before she became an Avenger.
    public Double popularity;	//4278.717
    @AuraEnabled
    public String poster_path;	///qAZ0pzat24kLdO3o8ejmbLxyOac.jpg
    @AuraEnabled
    public String release_date;	//2021-07-07
    public Integer revenue;	//318073697
    public Integer runtime;	//134
    public String status;	//Released
    public String tagline;	//Her world. Her secrets. Her legacy.
    @AuraEnabled
    public String title;	//Black Widow
    public boolean video;
    public Double vote_average;	//7.9
    public Integer vote_count;	//3466
}